"""
Django settings for dansah project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import environ

env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load dev.env only when running locally (Railway provides env vars directly)
_env_file = os.path.join(BASE_DIR, "dev.env")
if os.path.exists(_env_file):
    environ.Env.read_env(_env_file)
_environment = os.environ.get("ENVIROMENT", "DEV")
print("USING " + _environment + " SETTINGS")
IS_DEV = _environment == "DEV"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from SECRET_KEY env var (Railway), fallback to secret_key.txt (local dev)
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    _key_file = os.path.join(BASE_DIR, "secret_key.txt")
    if os.path.exists(_key_file):
        with open(_key_file) as f:
            SECRET_KEY = f.read().strip()
    else:
        raise ValueError("SECRET_KEY environment variable is not set and secret_key.txt not found.")

# SECURITY WARNING: don't run with debug turned on in production!
# Set ENABLE_DEBUG=False in Railway environment variables
DEBUG = os.environ.get("ENABLE_DEBUG", "False") == "True"
if IS_DEV:
    ALLOWED_HOSTS = ["localhost"]
else:
    ALLOWED_HOSTS = [os.environ.get("ALLOWED_HOST", "*"), "localhost"]
    _csrf_origin = os.environ.get("CSRF_TRUSTED_ORIGIN")
    if _csrf_origin:
        CSRF_TRUSTED_ORIGINS = [_csrf_origin]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "homeactivities",
    "homeevents",
    "homeministriesmaterial",
    "homeslider",
    "profiles",
    "quoteoftheday",
    "powerliving",
    "socialmedia",
    "prayerconnect",
    "prayercity",
    "leadershipinstitute",
    "contact",
    "home",
    "donation",
    "homeministries",
    "whitenoise.runserver_nostatic",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

# Frontend URL — set FRONTEND_URL env var in Railway dashboard to your Cloudflare Pages domain
_frontend_url = os.environ.get("FRONTEND_URL", "http://localhost:4200")
CORS_ORIGIN_WHITELIST = (
    "http://localhost:4200",
    _frontend_url,
)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    _frontend_url,
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "dansah.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dansah.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if IS_DEV:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("PGDATABASE"),
            "USER": env("PGUSER"),
            "PASSWORD": env("PGPASSWORD"),
            "HOST": env("PGHOST"),
            "PORT": env("PGPORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

USE_S3 = os.getenv("USE_S3") == "FALSE"

CORS_ORIGIN_ALLOW_ALL = True

STATIC_URL = "/static/"
# Extra places for collectstatic to find static files.
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = ("admin", os.path.join(BASE_DIR, "static", "admin"))

MEDIA_URL = "/media/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn", "media_root")

# AWS S3 — set these in Railway environment variables
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
AWS_S3_SIGNATURE_NAME = ("s3v4",)
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True
AWS_QUERYSTRING_AUTH = False
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"


# Cookie / HTTPS security — Railway serves over HTTPS in production
SESSION_COOKIE_SECURE = not IS_DEV
CSRF_COOKIE_SECURE = not IS_DEV
SECURE_SSL_REDIRECT = False   # Railway handles TLS termination upstream
SECURE_HSTS_SECONDS = 0
